#!/usr/bin/env python3
"""Run stratified sampling and rule-based reference-annotator agreement metrics.

This is NOT a human validation study. The reference labels are generated by the
deterministic keyword-rule protocols in ``analysis.validation_labeling``. The
resulting metrics measure agreement between the LLM extraction pipeline and an
independent, reproducible rule-based reference (a reproducibility floor). To run
a real human validation, replace the auto-labeled reference columns in the
sample CSV with human annotations and pass ``--no-auto-labels``.
"""

from __future__ import annotations

import argparse
import csv
import logging
import sys
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from _bootstrap import bootstrap_project

PROJECT_ROOT = bootstrap_project(include_infrastructure=True)

from analysis.validation_labeling import (
    apply_primary_rule_protocol,
    apply_secondary_rule_protocol,
)
from analysis.validation_metrics import classify_error, write_validation_metrics
from analysis.validation_sample import (
    build_stratified_sample,
    load_labels_csv,
    write_sample_csv,
)

logger = logging.getLogger(__name__)


def _apply_rule_reference_labels(sample_path: Path) -> list[dict[str, str]]:
    """Fill reference columns using the two deterministic rule protocols.

    These are rule-based reference annotators, not humans. Rows that already
    carry non-empty ``ref_triage`` (e.g. a real human annotation) are left
    untouched so a genuine gold set can be merged in later.
    """
    rows = load_labels_csv(sample_path)
    for row in rows:
        if row.get("ref_triage"):
            continue
        abstract = row.get("abstract_excerpt", "")
        hypothesis_id = row.get("hypothesis_id", "")
        primary = apply_primary_rule_protocol(abstract, hypothesis_id)
        secondary = apply_secondary_rule_protocol(abstract, hypothesis_id)
        row["ref_triage"] = primary.triage
        row["ref_evidence_status"] = primary.evidence_status
        row["ref_evidence_type"] = primary.evidence_type
        row["ref_source_claim"] = primary.source_claim
        row["secondary_triage"] = secondary.triage
        row["secondary_evidence_status"] = secondary.evidence_status
        row["secondary_evidence_type"] = secondary.evidence_type
        row["error_type"] = classify_error(row)
    return rows


def _write_labeled_csv(rows: list[dict[str, str]], path: Path) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    logging.basicConfig(level=logging.INFO)
    parser = argparse.ArgumentParser(description="Validation study orchestrator")
    parser.add_argument("--output-dir", default=str(PROJECT_ROOT / "output"))
    parser.add_argument("--sample-fraction", type=float, default=0.10)
    parser.add_argument("--min-size", type=int, default=200)
    parser.add_argument(
        "--no-auto-labels",
        dest="auto_labels",
        action="store_false",
        default=True,
        help="Skip rule-based reference auto-labeling (use pre-filled human labels).",
    )
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    data_dir = output_dir / "data"
    validation_dir = output_dir / "validation"
    validation_dir.mkdir(parents=True, exist_ok=True)

    nanopub_path = data_dir / "nanopublications.jsonl"
    corpus_path = data_dir / "corpus.jsonl"
    if not nanopub_path.exists() or not corpus_path.exists():
        logger.error("Missing corpus or nanopublications under %s", data_dir)
        return 1

    sample_path = validation_dir / "sample.csv"
    sample = build_stratified_sample(
        nanopub_path,
        corpus_path,
        fraction=args.sample_fraction,
        min_size=args.min_size,
    )
    write_sample_csv(sample, sample_path)
    logger.info("Wrote stratified sample (%d rows) → %s", len(sample), sample_path)

    if args.auto_labels:
        labeled = _apply_rule_reference_labels(sample_path)
        # Single labeled artifact: both reference columns are rule-generated, so
        # there is no separate human file to write (the old code wrote two
        # identical copies, falsely implying two independent annotators).
        labeled_path = validation_dir / "labels_rule_reference.csv"
        _write_labeled_csv(labeled, labeled_path)
        metrics_path = output_dir / "reports" / "validation_metrics.json"
        metrics = write_validation_metrics(labeled, metrics_path)
        data_metrics = data_dir / "validation_metrics.json"
        write_validation_metrics(labeled, data_metrics)
        logger.info("Validation metrics: %s", metrics)
        print(str(metrics_path))

    print(str(sample_path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
