"""Default keyword definitions for the 8-domain subfield taxonomy."""

from __future__ import annotations

DEFAULT_SUBFIELDS: dict[str, dict] = {
    "A1_formal": {
        "keywords": [
            # Mathematical structures and methods
            "category theory",
            "information geometry",
            "bayesian mechanics",
            "markov blanket",
            "stochastic",
            "langevin",
            "gauge theory",
            "path integral",
            "differential equation",
            "dynamical system",
            "fixed point",
            "convergence",
            "ergodic",
            "measure theory",
            "manifold",
            "lie group",
            # Formal reasoning indicators
            "theorem",
            "proof",
            "lemma",
            "corollary",
            "proposition",
            "derivation",
            "formalism",
            "formulation",
            "analytical",
            # Variational and optimization formalism
            "variational inference",
            "variational bound",
            "kl divergence",
            "kullback-leibler",
            "elbo",
            "evidence lower bound",
            "laplace approximation",
            "mean field",
            "message passing",
            "belief propagation",
            "expectation propagation",
            # Statistical mechanics and physics formalism
            "partition function",
            "hamiltonian",
            "lagrangian",
            "entropy production",
            "fluctuation theorem",
            "ito",
            "fokker-planck",
            "helmholtz",
            # Probability and inference formalism
            "posterior",
            "prior",
            "likelihood",
            "marginal",
            "conjugate",
            "sufficient statistic",
            "exponential family",
            "dirichlet",
            "state space model",
            # Mathematical notation indicators
            "equation",
            "matrix",
            "eigenvalue",
            "jacobian",
            "hessian",
            "gradient descent",
            "optimization",
            "objective function",
            "loss function",
        ],
        "description": "A1: Quantitative and formal mathematical theory",
        "priority": 3,  # Lower priority than C/B (checked after specific domains)
    },
    "A2_philosophy": {
        "keywords": [
            # Genuinely philosophical and qualitative terms
            "phenomenology",
            "epistemology",
            "ontology",
            "enactivism",
            "4e cognition",
            "embodied cognition",
            "extended mind",
            "predictive processing",
            "bayesian brain",
            "ecological psychology",
            "affordance",
            "niche construction",
            "autopoiesis",
            "sense-making",
            "consciousness",
            "qualia",
            "intentionality",
            "teleology",
            "reductionism",
            "emergence",
            "self-organization",
            "autonomy",
            "agency",
            "normativity",
            "naturalism",
            # General FEP/AIF terms (catch-all when no specific domain matches)
            "free energy principle",
            "active inference",
            "generative model",
        ],
        "description": "A2: Qualitative philosophy and general FEP theory",
        "priority": 4,  # Lowest priority — catch-all
    },
    "B_tools": {
        "keywords": [
            "planning",
            "reinforcement learning",
            "deep active inference",
            "neural network",
            "amortized",
            "scalable",
            "monte carlo",
            "tree search",
            "benchmark",
            "implementation",
            "library",
            "software",
            "framework",
            "toolkit",
            "open source",
            "api",
            "algorithm",
            "gymnasium",
            "environment",
        ],
        "description": "B: Tools and translation methods development",
        "priority": 2,
    },
    "C1_neuroscience": {
        "keywords": [
            "neural",
            "cortical",
            "hippocampal",
            "eeg",
            "fmri",
            "neuroimaging",
            "synaptic",
            "dopamine",
            "spiking",
            "prefrontal",
            "basal ganglia",
            "cerebellum",
            "thalamus",
            "electrophysiology",
            "meg",
            "bold",
            "brain imaging",
            "neuron",
            "dendrit",
        ],
        "description": "C1: Computational and systems neuroscience",
        "priority": 1,
    },
    "C2_robotics": {
        "keywords": [
            "robot",
            "sensorimotor",
            "motor control",
            "embodied",
            "navigation",
            "manipulation",
            "actuator",
            "simulator",
            "gazebo",
            "ros ",
            "control loop",
            "pid",
            "end effector",
            "gripper",
        ],
        "description": "C2: Robotics and embodied agents",
        "priority": 1,
    },
    "C3_language": {
        "keywords": [
            "language",
            "linguistic",
            "speech",
            "semantic",
            "reading",
            "communication",
            "natural language",
            "syntax",
            "morphology",
            "phonology",
            "discourse",
            "pragmatics",
            "transformer",
            "large language model",
            "llm",
            "tokeniz",
        ],
        "description": "C3: Language processing and communication",
        "priority": 1,
    },
    "C4_psychiatry": {
        "keywords": [
            "psychiatric",
            "schizophrenia",
            "depression",
            "autism",
            "anxiety",
            "psychosis",
            "computational psychiatry",
            "clinical",
            "disorder",
            "diagnosis",
            "symptom",
            "patient",
            "therapy",
            "treatment",
            "mental health",
            "ptsd",
            "ocd",
            "bipolar",
            "addiction",
        ],
        "description": "C4: Computational psychiatry and clinical applications",
        "priority": 1,
    },
    "C5_biology": {
        "keywords": [
            "morphogenesis",
            "cell",
            "organism",
            "evolution",
            "life",
            "autopoiesis",
            "biological",
            "developmental",
            "gene",
            "protein",
            "metabolism",
            "homeostasis",
            "ecological",
            "phenotype",
            "genotype",
            "fitness",
            "adaptation",
            "species",
        ],
        "description": "C5: Biology and morphogenesis",
        "priority": 1,
    },
}
